### ISSUE TITLE
retry workflow on failure option

### ISSUE THREAD

**Issue by BenBlaisdell** [RetailMeNotSandbox/dart#43]
Is there currently support for this?

**Comment by maybeiambatman** [comment]
So, before we actually do the work for this and push things in I want to address if this is really the way to go here.

The reason this issue was created is because one of our users suggested it. She would like to leverage this trigger as a way to retry her workflows.

I want to make sure every one else agrees that a general purpose on failure trigger is the better option than creating a retry feature in dart. e.g. have a new field in workflow called "retry" where retry is an number denoting how many times we are going to retry until successful run.

Thoughts? @dannymcpherson

**Comment by dannymcpherson** [comment]
This is a tough one... though I definitely lean more towards a failure trigger than a "retry" setting.  I'd like to hear more about the user's situation.  In general, what do users do today on failure?  I would assume they get an email and then have to manually retry.  Correct?

As for this implementation, a few things come to mind:

1. Will the failure trigger be used to retry the same workflow?
1. If so, are we okay with a potential infinite loop of failures?
1. Should we make these triggers stateful?  (e.g. maybe decrement a retry count... if it gets to zero within some time threshold, it "breaks" requiring user intervention.  I think this warrants some discussion)

Maybe we just proceed with this as a v1 and pay attention to the use cases that pop up.  Thoughts?

**Comment by maybeiambatman** [comment]
I agree. 

1. From what I hear from users so far this will be the main use case.
2/3. I think making the triggers stateful is a good first pass to approach this problem.

**Comment by BenBlaisdell** [comment]
For a simple case where wf X fails and triggers itself it's easy to implement a backoff feature after some number of attempts. However when we trigger a different workflow it gets a little fuzzier what we want to happen if that or another wf down the line fail. Or even if the original workflow is run again later in this chain and fails a second time. Now we're looking at loop detection and functionality that is starting to sound confusing to users.

Since the main usecase of this is rerunning a failed workflow I'm going to instead implement a retries_on_failure field on workflows.

**Comment by BenBlaisdell** [comment]
https://jira.rmn.com/browse/DW-4750

**Comment by dannymcpherson** [comment]
👍

**Comment by maybeiambatman** [comment]
Looks good 👍
