### ISSUE TITLE
Perform server side validation on AWS CRON expressions for Scheduled Triggers

### ISSUE THREAD

**Issue by maybeiambatman** [RetailMeNotSandbox/dart#9]
Follow-up issue from #3

**Comment by maybeiambatman** [comment]
AWS has a specific edge case around accepting cron values in the day-of-month and day-of-week fields.

Their documentation specifically states:

> Support for specifying both a day-of-week and a day-of-month value is not complete (you must currently use the '?' character in one of these fields).

Unfortunately, they don't validate this specific format when creating cloudwatch rules. As a result, we create some triggers on dart at times that are successfully created as rules on cloudwatch. But these never fire as they don't recognize the expression as valid.

I created a function to validate this edge case. Documentation link below if anyone is interested.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/ScheduledEvents.html

**Comment by maybeiambatman** [comment]
@ophiradi could you review this. Thanks!

**Comment by ophiradi** [comment]
I understand the change and it makes sense, however I have a few style comments:
1. Can you please rebase the three commits to one? 

2. If you make such a change - you might want to had a link to where the problem is stated (in a comment or the exception itself).  E.g. 
>>> import croniter
>>> import datetime
>>> now = datetime.datetime.now()
>>> cron = croniter.croniter('45 17 */2  * Mon', now)
>>> cron.get_next(datetime.datetime) 
it shows specifying day of week and day of month work - albeit incorrectly.

3. Maybe it is a good opportunity to add a generic crontab validation on top of what you added?
E.g. Use the cronter from above:
cron = croniter.croniter('77 17 */2  * *', now)
  File "<stdin>", line 1, in <module>
  File "/Users/aophir/.virtualenvs/dart/lib/python2.7/site-packages/croniter/croniter.py", line 131, in __init__
    expr_format))
ValueError: [77 17 */2  * *] is not acceptable, out of range

**Comment by maybeiambatman** [comment]
First of all, we always rebase commits before merging them in. I just didn't bother with this one since it's such a small change. I will definitely do it.

1. Since this is something that slips through AWS api, it doesn't really throw an exception. What would you have it point to in this case?

2. I have thought about this. The thing is, AWS has a very specific cron expression format that it accepts. I would rather let them handle the validation. This specific validation that I am committing is just something that slips through their cracks. I understand the risk though, we may not be aware of other validation overlooks that AWS doesn't check for. Would love an opinion on this @geota @jsteigel-rmn @dannymcpherson. I am worried about cronter rejecting an expression that AWS would have accepted.

**Comment by maybeiambatman** [comment]
After a discussion with @geota and @ophiradi we have decided to not include ```croniter``` or any cron validator inside dart. We'll let AWS carry that responsibility. Closing this.
